#!/bin/sh
# Remove older versions of docker
#sudo apt-get remove docker docker-engine docker.io containerd runc
curl https://get.docker.com | sh
sudo systemctl start docker && sudo systemctl enable docker
sudo usermod -aG docker brobey
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt-get update
sudo apt-get install -y nvidia-docker2
sudo systemctl restart docker
#test nvidia gpu in a docker container
sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi
