all: StreamTriad

NVCC = nvcc
#NVCC_FLAGS = -arch=sm_30
CUDA_LIB=`which nvcc | sed -e 's!/bin/nvcc!!'`/lib

%.o : %.cu
	${NVCC} ${NVCC_FLAGS} -c $< -o $@

StreamTriad: StreamTriad.o timer.o
	${CXX} -o $@ $^ -L${CUDA_LIB} -lcudart

clean:
	rm -rf StreamTriad *.o Makefile
