all: StreamTriad

CXX = hipcc

CUDA_PATH = /projects/opt/centos7/cuda/10.1/

%.cc : %.cu
	hipify-clang $^ > $@ --cuda-path=${CUDA_PATH} 

StreamTriad.o: StreamTriad.cc

StreamTriad: StreamTriad.o timer.o
	${CXX} -o $@ $^ 

clean:
		rm -rf StreamTriad *.o StreamTriad.cc
